settings = {
    'mleancop_dir': './prover_install/mleancop13/',
    'mleantap_path': './prover_install/mleantap13/mleantap13_swi.pl',
    'leo3_jar_path': './prover_install/leo3/leo3.jar',
    'tpg_dir': './prover_install/ntpg/',
    'java_path': 'java',
    'swipl_path': 'swipl',
    'node_path': 'node',
    'formula_pickle_path': 'full.pickle',
    'output_file_path': 'results.csv',
    'logic': 's5',
    'domain': 'vary',
    'timeout': 10,
    'theoremThreshold': 1,
    'nonTheoremThreshold': 1,
}
