settings = {
    'mleancop_dir': './prover_install/mleancop13/',
    'mleantap_path': './prover_install/mleantap13/mleantap13_swi.pl',
    'leo3_jar_path': './prover_install/leo3/leo3.jar',
    'tpg_dir': './prover_install/ntpg/',
    'java_path': '/usr/bin/java',
    'swipl_path': '/usr/bin/swipl',
    'node_path': '/usr/bin/node',
    'formula_pickle_path': 'formulas.pickle',
    'output_file_path': 'results.csv',
    'logic': 's5',
    'domain': 'const',
    'timeout': 10,
    'theoremThreshold': 2,
    'nonTheoremThreshold': 2,
}
